<?php
$blogs = $block->getCollection();
?>
<div class="blog-collection-wrapper">
    <div class="blog-published">
        <?php
        foreach ($blogs as $blog) { ?>
            <div class="blog-item">
                <div class="blog-item-title">
                    <a href="<?= $block->getUrl('blog/index/view', ['id'=>$blog->getId()])?>"><?= $blog->getTitle(); ?></a>
                </div>
                <div class="blog-item-details">
                    <div><?= __("Created At:") . ' ' . $block->getFormattedDate($blog->getCreatedAt()); ?></div>
                    <div><?= __("Author:") . ' ' . $block->getAuthor($blog->getUserId()); ?></div>
                </div>
                <div class="blog-item-content">
                    <?= strlen($blog->getContent())<100 ? $blog->getContent() : substr($blog->getContent(), 0, 100) . '...'; ?>
                    <div class="blog-item-view">
                        <a href="<?= $block->getUrl('blog/index/view', ['id'=>$blog->getId()])?>"><?= __('view'); ?></a>
                    </div>
                </div>
            </div>
            <?php
        } ?>
        <?= $block->getPagerHtml(); ?>
    </div>
</div>
