<?php
$blog = $block->getBlog();
?>
<div class="blog-container">
    <form class="blog-form" method="post" action="<?php echo $block->getUrl('blog/manage/save'); ?>" data-mage-init='{"validation": {}}'>
        <input type="hidden" name="id" value="<?= $blog->getId()?>"/>
        <div class="blog-form-field-container">
            <span class="blog-form-field-label"><?=__('Title')?>:</span>
            <label>
                <input type="text" name="title" class="required-entry blog-form-field" value="<?= $blog->getTitle(); ?>"/>
            </label>
        </div>
        <div class="blog-form-field-container">
            <span class="blog-form-field-label"><?=__('Content')?>:</span>
            <label>
                <textarea name="content" class="required-entry validate-no-html-tags blog-form-field" rows="10"><?= $blog->getContent(); ?></textarea>
            </label>
        </div>
        <div class="blog-form-action-container">
            <button type="submit" class="blog-form-action"><?=__('Submit')?></button>
        </div>
    </form>
</div>
